/**:
  ros__parameters:
    object_name: 002_master_chef_can
    geometry_path: "../../../assets/ycb/002_master_chef_can/model.obj"
    texture_path: "../../../assets/ycb/002_master_chef_can/texture_map.png"
    mesh_use_embedded_materials: true
    geometry_unit_in_meter: 1.0
    geometry_counterclockwise: true
    geometry_enable_culling: false
    # Raw Google 16k mesh -> centered NVDU YCB body frame.
    geometry2body_pose: [
      0.86602501, -0.5,        0.0, 0.009908,
      0.0,         0.0,       -1.0, 0.069902,
      0.5,         0.86602501, 0.0, 0.016903,
      0.0,         0.0,        0.0, 1.0
    ]
    body_id: 2
    region_id: 2
    # [x, y, z, roll, pitch, yaw], with angles in radians.
    initial_pose: [0.0, 0.0, 0.5, 1.5708, 0.0, 0.0]
    gt_initial_pose: [0.0, 0.0, 0.5, 1.5708, 0.0, 0.0]
    translation_amplitude: [0.0, 0.0, 0.0]
