/**:
  ros__parameters:
    object_name: cylinder
    geometry_path: "../../assets/cylinder/model.obj"
    mesh_use_embedded_materials: true
    geometry_unit_in_meter: 1.0
    geometry_counterclockwise: true
    geometry_enable_culling: false
    geometry2body_pose: [
      1.0, 0.0, 0.0, 0.0,
      0.0, 1.0, 0.0, 0.0,
      0.0, 0.0, 1.0, 0.0,
      0.0, 0.0, 0.0, 1.0
    ]
    body_id: 200
    region_id: 200
    # [x, y, z, roll, pitch, yaw], with angles in radians.
    initial_pose: [0.0, 0.0323408, 0.323408, 0.0, 0.0, 0.0]
